name: TCP over UDP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  submodule-ci:
    uses: eomielan/tcp-over-udp/.github/workflows/ci.yml@main
    with:
      working-directory: 'backend/tcpOverUdp'
  