name: TCP over UDP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  initialize-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: Verify makefile
        run: ls -la backend/tcpOverUdp

  submodule-ci:
    uses: eomielan/tcp-over-udp/.github/workflows/ci.yml@main
    with:
      working-directory: 'backend/tcpOverUdp'
  