name: TCP over UDP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  submodule-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Initialize submodule
        run: git submodule update --init --recursive

      - name: Call submodule CI workflow
        uses: eomielan/tcp-over-udp/.github/workflows/ci.yml@main
        with:
          working-directory: 'backend/tcpOverUdp'
  